## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("A =\n",A)
print("B =\n",B) 

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B =
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [2]:
#matrix multiplication
R1 = np.dot(A,B)
print(R1)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## Write a NumPy program to compute the determinant of a given square array

In [3]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("A =\n",A)

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Determinant of the said 2-D array
print(np.linalg.det(A))

6.66133814775094e-16


## Write a NumPy program to compute the cross product of two given vectors

In [5]:
import numpy as np
A = np.array([[1,2,3],
    [4,5,6],
    [7,8,9]
     ])
B = np.array([[9,8,7],
     [6,5,4],
     [3,2,1]
     ])
print("A =\n",A)
print("B =\n",B) 

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B =
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [6]:
R1 = np.cross(A, B)
R2 = np.cross(B, A)
#cross product of two vectors(A, B)
print("R1=\n", R1)
#cross product of two vectors(B,A)
print("R2=\n", R2)

R1=
 [[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]
R2=
 [[ 10 -20  10]
 [ 10 -20  10]
 [ 10 -20  10]]


## Write a NumPy program to compute the condition number of a given matrix

In [7]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("A =\n", A) 

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#condition number of the matrix
from numpy import linalg as LI
print(LI.cond(A))

3.813147060626918e+16


## Write a NumPy program to compute the inverse of a given matrix

In [9]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("A =\n",A) 

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#Inverse of the matrix
R1 =  np.linalg.inv(A)
print(R1)

[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
