### third argument of the 
### tensordot() method

In [ ]:
This can be a scalar as well as an array-like object. This indicates the axes on which we have to find tensordot

### difference between tensor products and tensor dot product with example

## tensor products

In [ ]:
Tensor products provide a most “natural” method of combining two modules.
They may be thought of as the simplest way to combine modules in a meaningful
fashion

## tensor products example

In [3]:
from sympy import Matrix
from sympy.physics.quantum import TensorProduct
m1 = Matrix([[1,2],[3,4]])
m2 = Matrix([[1,0],[0,1]])

In [4]:
TensorProduct(m1, m2)

Matrix([
[1, 0, 2, 0],
[0, 1, 0, 2],
[3, 0, 4, 0],
[0, 3, 0, 4]])

In [5]:
TensorProduct(m2, m1)

Matrix([
[1, 2, 0, 0],
[3, 4, 0, 0],
[0, 0, 1, 2],
[0, 0, 3, 4]])

## tensor dot product

In [ ]:
tensordot() is used to calculate the tensor dot product of two given tensors. 
ensordot() function sum the product of a’s elements and b’s elements over the axes specified by a_axes and b_axes. 

## tensor dot product example

In [2]:
# Programming example of tensordot when axes is an scalar
import numpy as np
# Declaring arrays
arr1 = np.arange(8).reshape(4, 2)
arr2 = np.arange(4, 12).reshape(2, 4)
print("Tensor1 is: ", arr1)
print("\nTensor2 is: ", arr2)

# Now we will calculate tensor dot
ans = np.tensordot(arr1, arr2, axes=1)
print("Tensordot of these tensors is:\n", ans)

Tensor1 is:  [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Tensor2 is:  [[ 4  5  6  7]
 [ 8  9 10 11]]
Tensordot of these tensors is:
 [[  8   9  10  11]
 [ 32  37  42  47]
 [ 56  65  74  83]
 [ 80  93 106 119]]
